
spring:
  security:
    filter:
      order: 10

  datasource:
    url: jdbc:h2:mem:customer-db
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000

      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
    open-in-view: false

logging:
  level:
    org.hibernate: debug

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-time: 86400000
  refresh-toke-expiration-time: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
