
spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:h2:mem:notification-db
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
    open-in-view: false

server:
  port: 8082


websocket:
  endpoint: /ws
  topic: /topic/notifications
  thread-pool:
    core-size: 5
    max-size: 10
    queue-capacity: 25
